name: Update heroicons

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current heroicons version
        run: echo "current_version=$(<.heroicons-version)" >> $GITHUB_ENV
      - name: Get latest github release
        id: latest_release
        uses: oprypin/find-latest-tag@v1
        with:
          repository: tailwindlabs/heroicons
          releases-only: true
      - name: Setup python
        if: ${{ steps.latest_release.outputs.tag != env.current_version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Get latest release
        if: ${{ steps.latest_release.outputs.tag != env.current_version }}
        run: python scripts/get-latest-heroicons.py
      - name: Create pull request
        if: ${{ steps.latest_release.outputs.tag != env.current_version }}
        uses: peter-evans/create-pull-request@v4
        with:
          branch: heroicons-${{ steps.latest_release.outputs.tag }}
          title: Update heroicons to ${{ steps.latest_release.outputs.tag }}
          commit-message: Update heroicons to ${{ steps.latest_release.outputs.tag }}
          body: |
            Update heroicons from ${{ env.current_version }} to ${{ steps.latest_release.outputs.tag }}.
            - [X] Update icons
            - [X] Update README
            - [ ] Update NuGet package version

            Don't forget to update the [NuGet package version](https://github.com/tmcknight/Blazor.Heroicons/blob/heroicons-${{steps.latest_release.outputs.tag}}/src/Blazor.Heroicons/Blazor.Heroicons.csproj) (if required) before merging this PR.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
